# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: app/router/command/command.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import marznode.backends.xray.api.proto.common.net.network_pb2
import marznode.backends.xray.api.proto.common.serial.typed_message_pb2
import marznode.backends.xray.api.proto.app.router.command.command_pb2


class RoutingServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SubscribeRoutingStats(self, stream: 'grpclib.server.Stream[app.router.command.command_pb2.SubscribeRoutingStatsRequest, app.router.command.command_pb2.RoutingContext]') -> None:
        pass

    @abc.abstractmethod
    async def TestRoute(self, stream: 'grpclib.server.Stream[app.router.command.command_pb2.TestRouteRequest, app.router.command.command_pb2.RoutingContext]') -> None:
        pass

    @abc.abstractmethod
    async def GetBalancerInfo(self, stream: 'grpclib.server.Stream[app.router.command.command_pb2.GetBalancerInfoRequest, app.router.command.command_pb2.GetBalancerInfoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def OverrideBalancerTarget(self, stream: 'grpclib.server.Stream[app.router.command.command_pb2.OverrideBalancerTargetRequest, app.router.command.command_pb2.OverrideBalancerTargetResponse]') -> None:
        pass

    @abc.abstractmethod
    async def AddRule(self, stream: 'grpclib.server.Stream[app.router.command.command_pb2.AddRuleRequest, app.router.command.command_pb2.AddRuleResponse]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveRule(self, stream: 'grpclib.server.Stream[app.router.command.command_pb2.RemoveRuleRequest, app.router.command.command_pb2.RemoveRuleResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/xray.app.router.command.RoutingService/SubscribeRoutingStats': grpclib.const.Handler(
                self.SubscribeRoutingStats,
                grpclib.const.Cardinality.UNARY_STREAM,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.SubscribeRoutingStatsRequest,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.RoutingContext,
            ),
            '/xray.app.router.command.RoutingService/TestRoute': grpclib.const.Handler(
                self.TestRoute,
                grpclib.const.Cardinality.UNARY_UNARY,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.TestRouteRequest,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.RoutingContext,
            ),
            '/xray.app.router.command.RoutingService/GetBalancerInfo': grpclib.const.Handler(
                self.GetBalancerInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.GetBalancerInfoRequest,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.GetBalancerInfoResponse,
            ),
            '/xray.app.router.command.RoutingService/OverrideBalancerTarget': grpclib.const.Handler(
                self.OverrideBalancerTarget,
                grpclib.const.Cardinality.UNARY_UNARY,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.OverrideBalancerTargetRequest,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.OverrideBalancerTargetResponse,
            ),
            '/xray.app.router.command.RoutingService/AddRule': grpclib.const.Handler(
                self.AddRule,
                grpclib.const.Cardinality.UNARY_UNARY,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.AddRuleRequest,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.AddRuleResponse,
            ),
            '/xray.app.router.command.RoutingService/RemoveRule': grpclib.const.Handler(
                self.RemoveRule,
                grpclib.const.Cardinality.UNARY_UNARY,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.RemoveRuleRequest,
                marznode.backends.xray.api.proto.app.router.command.command_pb2.RemoveRuleResponse,
            ),
        }


class RoutingServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SubscribeRoutingStats = grpclib.client.UnaryStreamMethod(
            channel,
            '/xray.app.router.command.RoutingService/SubscribeRoutingStats',
            marznode.backends.xray.api.proto.app.router.command.command_pb2.SubscribeRoutingStatsRequest,
            marznode.backends.xray.api.proto.app.router.command.command_pb2.RoutingContext,
        )
        self.TestRoute = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.router.command.RoutingService/TestRoute',
            marznode.backends.xray.api.proto.app.router.command.command_pb2.TestRouteRequest,
            marznode.backends.xray.api.proto.app.router.command.command_pb2.RoutingContext,
        )
        self.GetBalancerInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.router.command.RoutingService/GetBalancerInfo',
            marznode.backends.xray.api.proto.app.router.command.command_pb2.GetBalancerInfoRequest,
            marznode.backends.xray.api.proto.app.router.command.command_pb2.GetBalancerInfoResponse,
        )
        self.OverrideBalancerTarget = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.router.command.RoutingService/OverrideBalancerTarget',
            marznode.backends.xray.api.proto.app.router.command.command_pb2.OverrideBalancerTargetRequest,
            marznode.backends.xray.api.proto.app.router.command.command_pb2.OverrideBalancerTargetResponse,
        )
        self.AddRule = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.router.command.RoutingService/AddRule',
            marznode.backends.xray.api.proto.app.router.command.command_pb2.AddRuleRequest,
            marznode.backends.xray.api.proto.app.router.command.command_pb2.AddRuleResponse,
        )
        self.RemoveRule = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.router.command.RoutingService/RemoveRule',
            marznode.backends.xray.api.proto.app.router.command.command_pb2.RemoveRuleRequest,
            marznode.backends.xray.api.proto.app.router.command.command_pb2.RemoveRuleResponse,
        )
